/* 项目与技能数据，取材自 github.com/sutharson-k 的公开仓库
   （已剔除空仓库、fork 仓库与作者标注为未完成的项目）。
   页面正文一律使用英文，仅本文件的注释保留中文。 */
#include "data.h"

const Project PROJECTS[] = {
    { "Chess Engine",
      "A browser-based chess game that runs fully\noffline, with a built-in minimax AI opponent.",
      "Highlight: 3 adjustable difficulty levels",
      "JavaScript",
      "https://github.com/sutharson-k/chess-engine",
      1 },
    { "AI Mafia Game",
      "Multiple AI agents debate, reason, and deceive\neach other - watch the whole match unfold live.",
      "Highlight: runs without any API key",
      "Python",
      "https://github.com/sutharson-k/ai-mafia-game",
      0 },
    { "Automated Network Inventory",
      "Scans the local network and checks device\nhealth, alerting automatically via Discord / Slack.",
      "Highlight: real-time device health checks",
      "Python",
      "https://github.com/sutharson-k/Automated-Network-Inventory",
      0 },
    { "Real-Time Chat App",
      "Built with Node.js, Express, and Socket.io\nMulti-room support, presence, typing indicators.",
      "Highlight: message history playback",
      "Node.js",
      "https://github.com/sutharson-k/chat",
      0 },
    { "CLI Interview Chatbot",
      "A polished command-line chatbot for interview\nprep, with sentiment analysis and context tracking.",
      "Highlight: rich terminal UI via the Rich library",
      "Python",
      "https://github.com/sutharson-k/cli-chatbot",
      0 },
    { "Rule-Based Chatbot",
      "A terminal chatbot that recognizes greetings,\ncommon questions, and exit commands.",
      "Highlight: beginner-friendly rule engine",
      "Python",
      "https://github.com/sutharson-k/Codsoft-chatbot",
      0 },
    { "Movie Recommendation System",
      "A content-based recommendation engine using\nTF-IDF vectorization and cosine similarity.",
      "Highlight: built with scikit-learn",
      "Python",
      "https://github.com/sutharson-k/CODSOFT_recommendationsystem",
      0 },
    { "Dotsy CLI Tool",
      "A lightweight, efficient Python CLI tool,\npublished on PyPI.",
      "Highlight: supports Python 3.12+",
      "Python",
      "https://github.com/sutharson-k/dotsy",
      0 },
    { "Fesch AI Agent",
      "Rust core plus native C++ bindings and Python\nplugins - PC control, web automation, scheduling.",
      "Highlight: automatic OpenRouter model rotation",
      "Rust / C++ / Python",
      "https://github.com/sutharson-k/fesch",
      0 },
    { "Neon Shipping Hub",
      "A full-stack logistics app built with React and\nConvex, with a real-time database and auth.",
      "Highlight: Framer Motion animations",
      "TypeScript / React",
      "https://github.com/sutharson-k/neon-shipping-hub",
      0 },
    { "Sandify",
      "A full-stack marketplace connecting buyers,\nsuppliers, and transporters, with order tracking.",
      "Highlight: seller inventory & fleet management",
      "TypeScript / Convex",
      "https://github.com/sutharson-k/sand-project-2",
      0 },
    { "Smart Attendance System",
      "Combines ID card scanning and facial recognition\nfor dual-verified attendance tracking.",
      "Highlight: local SQLite database",
      "Python",
      "https://github.com/sutharson-k/smart-attendance",
      0 },
    { "Sonic Stream",
      "A streaming platform built with React and Convex,\nwith 3D visuals and smooth animations.",
      "Highlight: Shadcn UI component library",
      "TypeScript / React",
      "https://github.com/sutharson-k/sonic-stream",
      0 },
    { "Professional Task Manager",
      "Published on PyPI with full CI/CD and test\ncoverage - command-line task tracking.",
      "Highlight: Codecov coverage tracking",
      "Python",
      "https://github.com/sutharson-k/Task-Manager",
      0 },
    { "Tic-Tac-Toe AI",
      "An unbeatable minimax AI opponent, playable\nhead-to-head right in the terminal.",
      "Highlight: published on PyPI",
      "Python",
      "https://github.com/sutharson-k/tic-tac-toe-ai",
      0 },
};
const int PROJECT_COUNT = sizeof(PROJECTS) / sizeof(PROJECTS[0]);

const SkillGroup SKILL_GROUPS[] = {
    { "Programming Languages",
      "Python  |  JavaScript  |  TypeScript\nC  |  C++  |  Rust" },
    { "Frameworks & Tools",
      "Node.js  |  Express  |  React  |  Convex\nSDL2 / WebAssembly  |  Socket.io  |  Git" },
    { "Focus Areas",
      "AI & Machine Learning  |  Search Algorithms & Game AI\nNetwork Automation  |  Full-Stack Web Dev  |  CLI Tools" },
};
const int SKILL_GROUP_COUNT = sizeof(SKILL_GROUPS) / sizeof(SKILL_GROUPS[0]);
