/* 项目与技能数据，取材自 github.com/sutharson-k 的公开仓库
   （已剔除空仓库、fork 仓库与作者标注为未完成的项目）。 */
#include "data.h"

const Project PROJECTS[] = {
    { "国际象棋对战引擎",
      "浏览器内可离线运行的国际象棋游戏\n内置极小极大搜索 AI 对手，可直接试玩",
      "亮点：三档难度可调",
      "JavaScript",
      "https://github.com/sutharson-k/chess-engine",
      1 },
    { "AI 卧底游戏",
      "多个 AI 智能体互相博弈、推理与欺骗\n实时网页界面观战整场对局",
      "亮点：无需 API Key 也能运行",
      "Python",
      "https://github.com/sutharson-k/ai-mafia-game",
      0 },
    { "网络设备自动巡检系统",
      "自动扫描局域网设备并检测健康状态\n异常时通过 Discord / Slack 自动告警",
      "亮点：设备健康状态实时监测",
      "Python",
      "https://github.com/sutharson-k/Automated-Network-Inventory",
      0 },
    { "实时聊天应用",
      "基于 Node.js、Express 与 Socket.io\n支持多聊天室、在线状态与输入提示",
      "亮点：支持消息历史回放",
      "Node.js",
      "https://github.com/sutharson-k/chat",
      0 },
    { "命令行面试助手机器人",
      "面向面试场景的专业级 CLI 聊天机器人\n具备情感分析与对话上下文管理",
      "亮点：Rich 库打造终端界面",
      "Python",
      "https://github.com/sutharson-k/cli-chatbot",
      0 },
    { "规则式聊天机器人",
      "终端交互的基础聊天机器人\n可识别问候、常见提问与退出指令",
      "亮点：入门级规则引擎",
      "Python",
      "https://github.com/sutharson-k/Codsoft-chatbot",
      0 },
    { "电影推荐系统",
      "基于 TF-IDF 与余弦相似度\n的内容推荐算法实现",
      "亮点：基于 scikit-learn 实现",
      "Python",
      "https://github.com/sutharson-k/CODSOFT_recommendationsystem",
      0 },
    { "Dotsy 命令行工具",
      "已发布至 PyPI 的 Python CLI 工具\n轻量高效的开发者效率工具",
      "亮点：支持 Python 3.12+",
      "Python",
      "https://github.com/sutharson-k/dotsy",
      0 },
    { "Fesch 多语言 AI 智能体",
      "Rust 核心 + C++ 原生绑定 + Python 插件\n支持电脑控制、网页自动化与任务调度",
      "亮点：OpenRouter 模型自动切换",
      "Rust / C++ / Python",
      "https://github.com/sutharson-k/fesch",
      0 },
    { "Neon Shipping Hub",
      "基于 React + Convex 的全栈物流管理应用\n实时数据库与用户身份认证",
      "亮点：Framer Motion 动效",
      "TypeScript / React",
      "https://github.com/sutharson-k/neon-shipping-hub",
      0 },
    { "Sandify 建筑用砂交易平台",
      "连接买家、供应商与运输方的全栈市场\n支持下单、审核流程与实时物流追踪",
      "亮点：卖家库存与车队管理",
      "TypeScript / Convex",
      "https://github.com/sutharson-k/sand-project-2",
      0 },
    { "智能考勤系统",
      "结合 ID 卡扫描与人脸识别双重验证\n自动生成 Excel 考勤报表",
      "亮点：SQLite 本地数据库",
      "Python",
      "https://github.com/sutharson-k/smart-attendance",
      0 },
    { "Sonic Stream 音乐流媒体",
      "基于 React + Convex 的流媒体播放平台\n包含三维视觉效果与流畅动效",
      "亮点：Shadcn UI 组件库",
      "TypeScript / React",
      "https://github.com/sutharson-k/sonic-stream",
      0 },
    { "专业任务管理工具",
      "已发布至 PyPI，配有完整 CI/CD 与测试覆盖率\n命令行任务管理与进度追踪",
      "亮点：Codecov 覆盖率追踪",
      "Python",
      "https://github.com/sutharson-k/Task-Manager",
      0 },
    { "井字棋 AI 对战",
      "基于极小极大算法的不可战胜 AI 对手\n命令行终端人机对战",
      "亮点：已发布至 PyPI",
      "Python",
      "https://github.com/sutharson-k/tic-tac-toe-ai",
      0 },
};
const int PROJECT_COUNT = sizeof(PROJECTS) / sizeof(PROJECTS[0]);

const SkillGroup SKILL_GROUPS[] = {
    { "编程语言",
      "Python  ·  JavaScript  ·  TypeScript\nC  ·  C++  ·  Rust" },
    { "框架与工具",
      "Node.js  ·  Express  ·  React  ·  Convex\nSDL2 / WebAssembly  ·  Socket.io  ·  Git" },
    { "领域方向",
      "人工智能与机器学习  ·  搜索算法与游戏 AI\n网络自动化  ·  全栈 Web 开发  ·  命令行工具" },
};
const int SKILL_GROUP_COUNT = sizeof(SKILL_GROUPS) / sizeof(SKILL_GROUPS[0]);
